// The theaters on the site: independent and nonprofit cinemas in and around
// Seattle. No AMC, Regal, Cinemark or Landmark.
//
// favorite: true marks the theaters he follows most closely. They get red
// pins on the map, come first in every list, and have a "Favorites only" filter.
//
// To add a theater: add it here, write a source in scraper/sources/ that
// returns screenings with its id, and register the source in scraper/sources/index.js.

export const THEATERS = [
  {
    id: 'siff-downtown',
    favorite: true,
    name: 'SIFF Cinema Downtown',
    short: 'SIFF Downtown',
    neighborhood: 'Downtown',
    address: '2100 4th Ave',
    lat: 47.6142,
    lng: -122.34135,
    url: 'https://www.siff.net/cinema/cinema-venues/siff-cinema-downtown',
    blurb: 'The old Cinerama: one enormous curved screen, now run by SIFF.',
  },
  {
    id: 'siff-uptown',
    favorite: true,
    name: 'SIFF Cinema Uptown',
    short: 'SIFF Uptown',
    neighborhood: 'Lower Queen Anne',
    address: '511 Queen Anne Ave N',
    lat: 47.62348,
    lng: -122.35711,
    url: 'https://www.siff.net/cinema/cinema-venues/siff-cinema-uptown',
    blurb: 'Three screens of first-run indie, foreign and documentary films.',
  },
  {
    id: 'siff-film-center',
    favorite: true,
    name: 'SIFF Film Center',
    short: 'Film Center',
    neighborhood: 'Lower Queen Anne',
    address: '167 Republican St, Seattle Center',
    lat: 47.62319,
    lng: -122.3546,
    url: 'https://www.siff.net/cinema/cinema-venues/siff-film-center',
    blurb: 'A small screening room at Seattle Center for series and one-offs.',
  },
  {
    id: 'grand-illusion',
    name: 'Grand Illusion Cinema',
    short: 'Grand Illusion',
    neighborhood: 'Lower Queen Anne',
    // Pop-up screenings at SIFF Film Center until the Varsity Theatre
    // (4329 University Way NE, University District, 47.66072, -122.31336)
    // reopens as the Grand Illusion's new home in late 2026.
    address: 'Pop-ups at SIFF Film Center, 167 Republican St',
    lat: 47.62295,
    lng: -122.35415,
    url: 'https://grandillusioncinema.org/',
    blurb: 'Seattle’s longest-running independent cinema, between homes and moving into the Varsity.',
  },
  {
    id: 'nwff',
    name: 'Northwest Film Forum',
    short: 'NWFF',
    neighborhood: 'Capitol Hill',
    address: '1515 12th Ave',
    lat: 47.61441,
    lng: -122.31707,
    url: 'https://nwfilmforum.org/',
    blurb: 'Nonprofit film arts center with two screens of indie, archival and local work.',
  },
  {
    id: 'central-cinema',
    favorite: true,
    name: 'Central Cinema',
    short: 'Central Cinema',
    neighborhood: 'Central District',
    address: '1411 21st Ave',
    lat: 47.61319,
    lng: -122.30529,
    url: 'https://www.central-cinema.com/',
    blurb: 'Dinner-and-a-movie house for cult classics, sing-alongs and new indies.',
  },
  {
    id: 'beacon',
    favorite: true,
    name: 'The Beacon',
    short: 'The Beacon',
    neighborhood: 'Columbia City',
    address: '4405 Rainier Ave S',
    lat: 47.56407,
    lng: -122.28837,
    url: 'https://thebeacon.film/',
    blurb: 'A 48-seat single screen programming repertory, genre and art-house films.',
  },
  {
    id: 'tasveer',
    favorite: true,
    name: 'Tasveer Film Center',
    short: 'Tasveer',
    neighborhood: 'Columbia City',
    address: '4812 Rainier Ave S',
    lat: 47.55899,
    lng: -122.28541,
    url: 'https://filmcenter.tasveer.org/',
    blurb: 'The old Ark Lodge, now showing South Asian and world cinema.',
  },
  {
    id: 'majestic-bay',
    favorite: true,
    name: 'Majestic Bay Theatres',
    short: 'Majestic Bay',
    neighborhood: 'Ballard',
    address: '2044 NW Market St',
    lat: 47.66886,
    lng: -122.3841,
    url: 'https://www.majesticbay.com/',
    blurb: 'Ballard’s family-owned three-screen neighborhood theater.',
  },
  {
    id: 'admiral',
    name: 'Admiral Theater',
    short: 'Admiral',
    neighborhood: 'West Seattle',
    address: '2343 California Ave SW',
    lat: 47.58197,
    lng: -122.38694,
    url: 'https://www.farawayentertainment.com/movie-theatres/seattle/washington/admiral-theater',
    blurb: 'A 1942 streamline moderne landmark showing new releases.',
  },
  {
    id: 'tin-room',
    favorite: true,
    name: 'The Tin Room',
    short: 'Tin Room',
    neighborhood: 'Burien',
    address: '923 SW 152nd St, Burien',
    lat: 47.46663,
    lng: -122.34688,
    url: 'https://tinroombar.com/',
    blurb: 'A bar and restaurant with its own small movie theater in back.',
  },
  {
    id: 'north-bend',
    favorite: true,
    name: 'North Bend Theatre',
    short: 'North Bend',
    neighborhood: 'North Bend',
    address: '125 Bendigo Blvd N, North Bend',
    lat: 47.49605,
    lng: -121.7868,
    url: 'https://www.northbendtheatre.com/',
    blurb: 'A 1941 single-screen theater in the Cascade foothills.',
  },
];

export const THEATER_IDS = new Set(THEATERS.map((t) => t.id));
